doctrine_migrations:
    migrations_paths:
        'App\Migrations': 'src/App'
    connection: default
    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'
    organize_migrations: BY_YEAR_AND_MONTH
    all_or_nothing: true
    check_database_platform: true
