config:
  index:
    dashboard:
      title: dashboard.title
      name: dashboard.name
      path: index
  home:
    edit:
      title: home.edit.title
      name: home.edit.name
      path: edit
  expense:
    index:
      title: expense.index.title
      name: expense.index.name
      path: index
