version: '2'

services:
    web:
        build: ./web
        container_name: roomies-web
        image: roomies-web
        ports:
            - ${APP_PORT}:80
        volumes:
            - ${APP_DIR}:/home/app:ro
        links:
            - php
        network_mode: bridge

    php:
        build: ./php
        container_name: roomies-php
        image: roomies-php
        links:
            - db
            - mailcatcher
            - rabbitmq
        volumes:
            - ${APP_DIR}:/home/app:cached
        network_mode: bridge
        working_dir: /home/app

    db:
        build: ./dbserver
        container_name: roomies-db
        image: roomies-db
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ${APP_DB}:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        network_mode: bridge

    mailcatcher:
        container_name: roomies-mail
        image: yappabe/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
        network_mode: bridge

    rabbitmq:
        container_name: roomies-rabbitmq
        image: rabbitmq:management
        ports:
            - "${RABBITMQ_QUEUE_PORT}:5672"
            - "${RABBITMQ_GUI_PORT}:15672"
        volumes:
            - ${APP_RABBITMQ}:/var/lib/rabbitmq:cached
        network_mode: bridge

    consumer:
        build: ./consumer
        container_name: roomies-consumer
        image: roomies-consumer
        links:
            - db
            - mailcatcher
            - rabbitmq
        volumes:
            - ${APP_DIR}:/home/app:cached
        network_mode: bridge
        working_dir: /home/app

