name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  php-quality-checks:
    name: PHP Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: PHP Code Sniffer
        if: ${{ always() }}
        run: |
          wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -q
          php phpcs.phar src/

      - name: PHP CS Fixer
        if: ${{ always() }}
        run: |
          wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.16.1/php-cs-fixer.phar -q
          php php-cs-fixer.phar fix src --dry-run --diff

      - name: PHP Mess Detector
        if: ${{ always() }}
        run: |
          wget https://phpmd.org/static/latest/phpmd.phar -q
          php phpmd.phar src/ text codesize,controversial,phpmd.xml

      - name: PHPStan
        if: ${{ always() }}
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse src/


  php-tests:
    name: PHP Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: PHP Unit Tests
        uses: php-actions/phpunit@master
        with:
          bootstrap: tests/bootstrap.php
          configuration: phpunit.xml.dist
          args: --coverage-text
