name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  php-quality-checks:
    name: PHP Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHP Code Sniffer
        if: ${{ always() }}
        run: vendor/bin/phpcs --standard=PSR2 src

      - name: PHP Mess Detector
        if: ${{ always() }}
        run: vendor/bin/phpmd src/ text codesize,controversial,phpmd.xml

      - name: PHPStan
        if: ${{ always() }}
        run: vendor/bin/phpstan analyse -c phpstan.neon

  php-tests:
    name: PHP Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: PHP Unit
        if: ${{ always() }}
        run: bin/phpunit
